# Generated by Django 3.2.5 on 2025-04-12 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220819_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_pin', to='api.thread', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pin', to=settings.AUTH_USER_MODEL, verbose_name='Закреплено пользователем'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_posts', to='api.thread', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Привет мир', max_length=500),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_threads', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='replyCount',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(max_length=128, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='topic',
            field=models.CharField(choices=[('1', 'Цели и задачи ВКР'), ('2', 'План работы'), ('3', 'Теоретические результаты'), ('4', 'Практические результаты'), ('5', 'Технологии'), ('6', 'Литература'), ('7', 'Презентация'), ('8', 'Общие вопросы')], default=1, max_length=32, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
